### ISSUE TITLE
Plugin won't compile with latest Adium release

### ISSUE THREAD

**Issue by rodneyrod** [duxet/adium-facebook#2]

**Comment by duxet** [comment]
The issue is that Adium fails to build on newest Mac OS 10.12 platform. And the another one issue is that Adium development seems to be dead, even their bug tracker is down 😞

**Comment by rodneyrod** [comment]
OpenSSL issue?

**Comment by mluis** [comment]
I'm getting

`/adiumPurpleCore.m:41:9: fatal error: 'auth.h' file not found`

**Comment by rodneyrod** [comment]
@duxet Have you had any luck with this one?

**Comment by mluis** [comment]
I'm getting

```
/tmp/adium-facebook/adium/Plugins/Purple Service/libpurple_extensions/auth_fb.c:23:10: fatal error: 'internal.h' file not found
#include "internal.h"
         ^~~~~~~~~~~~


** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/adium-facebook/adium/build/Adium.build/Debug/AdiumLibpurple.build/Objects-normal/x86_64/auth_gtalk.o /tmp/adium-facebook/adium/Plugins/Purple\ Service/libpurple_extensions/auth_gtalk.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Compiling like: 

`xcodebuild -configuration=release HEADER_SEARCH_PATHS="/usr/local/Cellar/openssl@1.1/1.1.1/include" OTHER_CFLAGS="$(pkg-config --cflags --libs glib-2.0)"`

**Comment by stevegwh** [comment]
> I'm getting
> 
> ```
> /tmp/adium-facebook/adium/Plugins/Purple Service/libpurple_extensions/auth_fb.c:23:10: fatal error: 'internal.h' file not found
> #include "internal.h"
>          ^~~~~~~~~~~~
> 
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /tmp/adium-facebook/adium/build/Adium.build/Debug/AdiumLibpurple.build/Objects-normal/x86_64/auth_gtalk.o /tmp/adium-facebook/adium/Plugins/Purple\ Service/libpurple_extensions/auth_gtalk.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> ```
> 
> Compiling like:
> 
> `xcodebuild -configuration=release HEADER_SEARCH_PATHS="/usr/local/Cellar/openssl@1.1/1.1.1/include" OTHER_CFLAGS="$(pkg-config --cflags --libs glib-2.0)"`

I'm getting exactly the same problem. The purple-facebook plugin works fine for me on Pidgin and I'd love to continue using it with Adium. I tried for about an hour to fix the errors but with little luck. Did you manage to get it working in the end?
